[[entries]]
pattern = "~/repos/isync(/.*)?"
flake_reference = "~/repos/contributed-projects-flakes/isync"

[[entries]]
pattern = "~/repos/matplotlib(/.*)?"
flake_reference = "~/repos/contributed-projects-flakes/matplotlib"

[[entries]]
pattern = "~/repos/scipp(/.*)?"
flake_reference = "~/repos/contributed-projects-flakes/scipp"

[[entries]]
pattern = "/home/doron/repos/pint(/.*)?"
flake_reference = "~/repos/contributed-projects-flakes/pint"

[[entries]]
pattern = "/home/doron/repos/hebcal-web(/.*)?"
flake_reference = "~/repos/contributed-projects-flakes/hebcal-web"
